#
//  ci_post_clone.sh
//  QueueIT
//
//  Created by Darragh Flynn on 18/03/2026.
//

#!/bin/sh

# 1. Navigate to your app's subdirectory
# Xcode Cloud starts at the root of your git repo
cd $CI_PRIMARY_REPOSITORY_PATH/QueueIT

# 2. Create the file from scratch
# This overwrites anything there, or creates it if it doesn't exist
cat <<EOF > Config-Release.xcconfig
// Generated by Xcode Cloud ci_post_clone.sh
SUPABASE_URL = $SUPABASE_URL
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
BACKEND_URL = $BACKEND_URL
EOF

cat <<EOF > Config-Debug.xcconfig
// Generated by Xcode Cloud ci_post_clone.sh
SUPABASE_URL = $SUPABASE_URL
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
BACKEND_URL = $BACKEND_URL
EOF

echo "✅ Config-Release.xcconfig + Debug.xcconfig has been created from environment variables."
