name: logging-tests

on:
  pull_request:
    paths:
      - "QueueITbackend/**"
  push:
    paths:
      - "QueueITbackend/**"

jobs:
  logging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: QueueITbackend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run logging tests
        run: pytest -q tests/test_logging_middleware.py

